---
- name: Checking if cloudfuse exists already
  stat:
    path: /usr/local/bin/cloudfuse
  register: cf_exists
  tags:
    - cf_clone

- name: Downloading cloudfuse from github to /tmp/
  git:
    repo: https://github.com/redbo/cloudfuse.git
    dest: /tmp/cloudfuse
    clone: yes
    update: yes
  register: cf_download
  when: cf_exists.stat.exists == False
  tags:
    - cf_clone
  check_mode: no

- name: Running ./configure on files
  command: './configure'
  args:
    chdir: /tmp/cloudfuse
  when: cf_exists.stat.exists == False
  tags:
    - cf_clone

- name: Running "make" on files
  make:
    chdir: /tmp/cloudfuse
  when: cf_exists.stat.exists == False
  tags:
    - cf_clone

- name: Running "make install" on files
  make:
    chdir: /tmp/cloudfuse
    target: install
  when: cf_exists.stat.exists == False
  tags:
    - cf_clone

- name: Clearing up old files
  file:
    state: absent
    path: /tmp/cloudfuse
  tags:
    - cf_cleanup
    - cf_clone
