---
- yum:
    state: latest
    name: 
      - git
      - gcc
      - make
      - fuse
      - fuse-devel
      - curl-devel
      - libxml2-devel
      - openssl-devel
      - json-c-devel
  tags:
    - cloudfuse_dependencies
    - cloudfuse
  when: ansible_distribution == "CentOS" or ansible_distribution == 'Red Hat Enterprise Linux'
