---
- name: Configure rackspace configuration file
  template:
    src: rackspace.j2
    dest: /root/.cloudfuse
    owner: root
    group: root
    mode: '0600'
  when: rackspace
  tags:
    - rack_cf_config

- name: Configure openstack configuration file
  template:
    src: openstack.j2
    dest: /root/.cloudfuse
    owner: root
    group: root
    mode: '0600'
  when: openstack
  tags:
    - openstack_cf_config
