---
- name: Configure rackspace configuration file
  template:
    src: rackspace.j2
    dest: /root/.cloudfuse
    owner: root
    group: root
    mode: '0600'
  when: rackspace
  tags:
    - cf_rack_config

- name: Configure openstack configuration file
  template:
    src: openstack.j2
    dest: /root/.cloudfuse
    owner: root
    group: root
    mode: '0600'
  when: openstack
  tags:
    - cf_openstack_config
