---
- name: Checking if cloudfuse already exists
  stat:
    path: /usr/local/bin/cloudfuse
  register: cf_exists
  tags:
    - cloudfuse_clone

- block:
  - name: "Nothing to do, exiting"
    debug:
      msg: "Cloudfuse binary exists, exiting" 
  - meta: end_play
  when: cf_exists.stat.exists == True

- name: Download cloudfuse git files
  git:
    repo: https://github.com/redbo/cloudfuse.git
    dest: /tmp/cloudfuse
    clone: yes
    update: yes
  register: cf_clone
  when: cf_exists.stat.exists == False
  tags:
    - cloudfuse_clone
