---
# tasks file for cloudfuse
- name: Skip if OS is supported
  fail:
    msg: This system is not supported
  when: ansible_os_family != "RedHat" and ansible_os_family != "Debian"
  tags:
    - always
- name: Install cloudfuse dependencies
  import_tasks: cloudfuse_deps.yml
  tags:
    - cf_deps
- name: Building cloudfuse
  import_tasks: building_cloudfuse.yml
  tags:
    - cf_build
- name: Creating Cloudfuse configuration file
  import_tasks: create_cloudfuse_config.yml
  tags:
    - cf_config_file
- name: Creating and mounting cloudfuse
  import_tasks: mount_cloudfuse.yml
  tags:
    - cf_mount
